### ISSUE TITLE
broken version 2.0.0-rc1

### ISSUE THREAD

**Issue by airtoxin** [Yomguithereal/baobab-react#101]
newest baobab-react version `2.0.0-rc1` in npm was broken.

I use higherOrder function with babelify
`import {root} from 'baobab-react/higher-order';`
It causes `Uncaught TypeError: Cannot read property 'root' of undefined`

<img width="839" alt="screenshot 2016-03-19 22 23 38" src="https://cloud.githubusercontent.com/assets/2460874/13898798/5521a524-ee21-11e5-9bf7-d861be7e7b3a.png">

I think `.default` is unnecessity https://github.com/Yomguithereal/baobab-react/blob/new-version/higher-order.js#L1

**Comment by Yomguithereal** [comment]
Hello @airtoxin. I am awfully sorry but it seems I forgot to publish this RC version using the `beta` tag. If you want to use the version documented on the master branch you should install the `1.0.1` version using `npm install baobab-react@1.0.1`.

However, if what you want is to use the latest dev version I am currently brewing, I'll be happy to debug the issue with you at the beginning of the week.

**Comment by airtoxin** [comment]
`1.0.1` works fine :)

I'm ok to debug

**Comment by Yomguithereal** [comment]
Hello again @airtoxin. I just published a new beta version of the v2. You can install it through:

```bash
npm install baobab-react@beta
```

If you want to upgrade, the docs can be found on the `new-version` branch [here](https://github.com/Yomguithereal/baobab-react/tree/new-version#baobab-react).

Basically, what changed is a simplification of the bindings and a more simple way to dispatch actions.

**Comment by airtoxin** [comment]
Hi @Yomguithereal. Sorry for delay.

I tried beta version, and got it. `Uncaught Error: baobab-react/higher-order.branch: given target is not a valid React component.`.
My application works fine in version 1.0.1

**Comment by airtoxin** [comment]
Ahh I see.
`higher-order` function changes interfaces from `branch(Component, cursors)` to `branch(cursors, Component)`.
I fixed my application code, and works fine :)

**Comment by Yomguithereal** [comment]
Good to know :). I'll close the issue then. The reason why I change the args' order is so the higher-order function now respects functional programming's philosophy (currying notably and the free decorator that comes with it).
