### ISSUE TITLE
2.0.0-rc1: es2015 preset dependency

### ISSUE THREAD

**Issue by magus** [Yomguithereal/baobab-react#102]
Looks like there is a dependency on es2015 preset in the latest release from npm?

Seeing an error in `baobab-react/mixins.js`
```Couldn't find preset "es2015" relative to directory...```

**Comment by Yomguithereal** [comment]
Hello @magus. That's strange indeed. The library doesn't need dependencies (except from your own Baobab and react, obviously) to be used and the released files are transpiled. Can you try to install `2.0.0-rc2` and tell me whether the problem persists please?

**Comment by mcharytoniuk** [comment]
It persists with React Native 0.25.1.

**Comment by Yomguithereal** [comment]
Does React Native installs relies on dev dependencies even if this is not needed?

**Comment by mcharytoniuk** [comment]
It's hard to say. It builds dependency graph based on node_modules require calls before running and it's possible that it parses package.json and interprets this: https://github.com/Yomguithereal/baobab-react/blob/cfa1ec5796079fdf2f5adad887fe1259244c1d01/package.json#L52 . It's only a guess though.

**Comment by Yomguithereal** [comment]
That's not impossible indeed but this would be quite strange for him to do so. Can you point me toward a library written in ES6 and used with react-native somewhere so I can try to find a solution?

**Comment by magus** [comment]
This popped up for me again...moment is ES6 but not using babel.

**Comment by magus** [comment]
After installing babel-preset-es2015 I'm seeing a new error...
![image](https://cloud.githubusercontent.com/assets/290084/15452319/83fe7c46-1f9f-11e6-937b-eb7f02fa6223.png)

**Comment by magus** [comment]
Had to install all the babel-preset dependencies to get things to build properly. Not sure I fully understand why or have the bandwidth to investigate.

```
"babel-preset-es2015": "^6.9.0",
"babel-preset-react": "^6.5.0",
"babel-preset-stage-1": "^6.5.0",
```

**Comment by Yomguithereal** [comment]
I am a bit lost here and don't know how I can help you further. Is your project open source somehow so I can try to reproduce the issue on my end?

**Comment by mcharytoniuk** [comment]
It would be enough to create an empty react-native project and use baobab-react inside. It crashes during library require call.

**Comment by Yomguithereal** [comment]
The issue seems to be related to react-native. See [this](https://github.com/feathersjs/feathers-commons/issues/9) issue for instance, or [this](https://github.com/facebook/react-native/issues/4548) one also. It would mean I need to put Babel configuration out of the package.json and ensure the config is not in the released package but this is quite annoying. Let me check the evolution of the problem on react-native's side.
