### ISSUE TITLE
Update index.js

### ISSUE THREAD

**Issue by lghiur** [Yomguithereal/baobab-react#105]
As wrappers and decorators functionality has been removed on 2.0.0-rc1 version, I think that index.js should be updated;

Current code:

module.exports = {
  decorators: require('./dist-modules/decorators.js').default,
  higherOrder: require('./dist-modules/higher-order.js').default,
  mixins: require('./dist-modules/mixins.js').default,
  PropTypes: require('./dist-modules/utils/prop-types.js').default,
  wrappers: require('./dist-modules/wrappers.js').default
};

Thank you,
Laurentiu

**Comment by Yomguithereal** [comment]
Hello @lghiur. This should not be the case from  `2.0.0-rc2` and onwards. Thanks for the heads up.
