### ISSUE TITLE
this.state is null

### ISSUE THREAD

**Issue by 222xiaohuan** [Yomguithereal/baobab-react#116]
Hi,

I wrote the demo according to the docs, but for some reason, it keeps give me the error, this.state is always null. attach my codes here:

![index](https://cloud.githubusercontent.com/assets/38194/15888600/14698f16-2d9a-11e6-9968-bfa55e03c30a.png)
![package](https://cloud.githubusercontent.com/assets/38194/15888599/14695e4c-2d9a-11e6-89e1-ad0f67797d8d.png)
![pokedex](https://cloud.githubusercontent.com/assets/38194/15888601/147263a2-2d9a-11e6-9306-f6060bb5e548.png)
![state tree](https://cloud.githubusercontent.com/assets/38194/15888602/149a5bfa-2d9a-11e6-9dcd-b4c5aa711111.png)

Any help will be appreciate , thanks very much!

**Comment by 222xiaohuan** [comment]
@Yomguithereal can you please help, thank you very much.

**Comment by psypersky** [comment]
Same problem here

**Comment by psypersky** [comment]
@222xiaohuan Change `class SomeClass extends Component` to `React.createClass`, still no sure exactly what is the difference or what is causing the problem, anyone has an idea?

**Comment by psypersky** [comment]
Got it!
```No Mixins
Unfortunately ES6 launched without any mixin support. Therefore, there is no support for mixins when you use React with ES6 classes. Instead, we're working on making it easier to support such use cases without resorting to mixins.```
https://facebook.github.io/react/docs/reusable-components.html#no-mixins

**Comment by 222xiaohuan** [comment]
@psypersky so that means we can't use this baobab-react in ES6 environment？or is there any solutions? thank you so much~ 👍

**Comment by psypersky** [comment]
Sure, use higher order components or decorators
[https://github.com/Yomguithereal/baobab-react/blob/master/docs/higher-order.md](url)

Im using decorators with the babel-plugin-transform-decorators-legacy

```
@branch({
  chat: ['chat'],
})

export default class Chat extends React.Component {

  static propTypes = {
    chat: React.PropTypes.object.isRequired,
  }...
```

**Comment by Yomguithereal** [comment]
@psypersky is right. If you want to use ES6 classes or pure function components, you can use the HOC or the decorators.
