### ISSUE TITLE
Branch decorator question

### ISSUE THREAD

**Issue by vcardins** [Yomguithereal/baobab-react#122]
I'm trying  
```js 
@branch({user: ['user', 'model']})
``` 
to get an user sub collection but it returns undefined. This works fine: 
```js
state.select(['user', 'model']).get())
```

What am I doing wrong?

**Comment by Yomguithereal** [comment]
Hello @vcardins. Without more context it's quite hard to answer your question. Is your code available somewhere?

**Comment by vcardins** [comment]
Thanks for the prompt response. Maybe a screenshot is worth a thousand words
![image](https://cloud.githubusercontent.com/assets/2383329/25410352/038883b8-29cb-11e7-9aa3-49e8bf186c80.png)
I use baobab in another project (mixim) and I'm able to do something like
cursors: {
	models: ['lookup', 'models'],
} 
If still unclear, I can create a gist.
Thank you very much !

**Comment by Yomguithereal** [comment]
Yes, a gist would be nice. With what you wrote, this.props.lookup, for instance, should be the data at the defined cursor not a cursor itself.

**Comment by vcardins** [comment]
Sorry, I haven't touched this project for last few days. So, please see here my gist: https://gist.github.com/vcardins/f7ddfc91039b40c18eff447441a5be46.
Thank you much for the support.

**Comment by Yomguithereal** [comment]
Did you correctly root your main component to the tree? What does your state file looks like?

**Comment by vcardins** [comment]
Hey, I just updated gist, please take a look. Basically, is it possible to get model data with something like:
```js 
@branch({user: ['user', 'model']})
``` ? My goal by using the HOC, have access to nested cursors data. Apologies if I'm misunderstanding something, I'm just starting with Baobab.

**Comment by Yomguithereal** [comment]
Well might be that your `user` object is empty or that your delaying the `.commit` is too late and a render without data happen before.

**Comment by vcardins** [comment]
It was an implementation mistake, it's working fine now. Closing ticket
