### ISSUE TITLE
Context access in higher order components

### ISSUE THREAD

**Issue by Yomguithereal** [Yomguithereal/baobab-react#13]
@bebraw, following up here:

I can't find a way to enable composed components to painlessly access the context or any object property correctly. Problem is the user should have access to the tree or the cursors if he wants to use them for whatever reason.

```js
class MyComponent extends Component {
  render() {
    console.log(this.context) >>> {}
    console.log(this.cursors) >>> undefined
  }
}

// hoc will have access to context and cursors but cannot propagate to
// the Composed Component
var ComposedComponent = hoc(Component);
```

I guess this is normal but this is quite hard to do anything without having the user explicitly define `contextPropTypes` which somewhat defeats the purpose of having component composition.

**Comment by Yomguithereal** [comment]
After taking a little stroll around the Internet, it seems that passing those things by context is customary. What a drag...

**Comment by bebraw** [comment]
Yeah, I suppose there's no nice way to pass context implicitly yet. That would have been nice as then a Branch would have been able to resolve `Root` easily.

**Comment by bebraw** [comment]
I wonder if it would make sense to push the problem elsewhere? You could have a factory that connects `Branch` hoc with root. Then you would connect the components against that.

This would take some extra code and add complications but just might work.

**Comment by bebraw** [comment]
What if we go with explicit passing now? Ie. pass `root` via a prop to children. At least that will work.

**Comment by bebraw** [comment]
One interesting benefit of this is that the `root` you pass can actually be a branch (just the cursor). This is just the way I work in my hierarchical demo. It's useful to be able to constrain cursor this way.

**Comment by Yomguithereal** [comment]
Passing the root is not an issue currently. As soon as your top level component is a Root, then your branches will receive the tree through context and will be able to function very well. The issue is if you want a branch composed component to be able to access the tree or cursors directly. Then you have to do the following:

```js
import {Branch} from 'baobab-react/higher-order';
import PropTypes from 'baobab-react/prop-types';

class MyComponent extends Component {
  constructor(props) {
    super(props);

    this.contextTypes = {
      tree: PropTypes.baobab,
      cursors: PropTypes.cursors
    };
  },
  render() {
    //... then you can access tree and cursors
    this.context.tree;
    this.context.cursors;

    return <div />;
  }
}

var ComposedComponent = Branch(MyComponent, {cursors: {...}});
```

Which is not that horrible but somewhat lacks of the mixins' simplicity.

**Comment by bebraw** [comment]
Would it be possible to push that `this.contextTypes` bit to a custom Component of our own?

```javascript
import {Branch, BaobabComponent} from 'baobab-react/higher-order';

class MyComponent extends BaobabComponent {
  constructor(props) {
    super(props);

    ...  // what if you want to modify contextTypes, though?
  },
  render() {
    //... then you can access tree and cursors
    this.context.tree;
    this.context.cursors;

    return <div />;
  }
}

var ComposedComponent = Branch(MyComponent, {cursors: {...}});
```

**Comment by Yomguithereal** [comment]
I didn't find any way to do so because the Composed Component is different from the component being composed.

**Comment by bebraw** [comment]
Ah, I see. Maybe we can go with a verbose API for now and see if we can figure something neater out later?

**Comment by Yomguithereal** [comment]
Yup, will do this for the time being and finish an initial version of each strategies as a starter.

**Comment by bebraw** [comment]
Would it be possible to set up a convention and push this to props? Example:

```javascript
@branch({
  cursors: function() {
    return {
      lane: ['lanes', this.props.index],
    };
  }
})
class Lane extends React.Component {
  constructor(props: {
    index: number;
  }) {
    super(props);
  }
  render() {
    var cursor = this.props.cursors.lane; // !!!
    var lane = this.props.lane;

    return (
      <div className='lane'>
        <div className='name'>{lane.name}</div>
          {/* passing parent reference here so the child can branch against that */}
          <Notes parent={cursor)} />
      </div>
    );
  }
}
```

This would solve a lot of problems for me.
