### ISSUE TITLE
Deprecated Methods in React 17

### ISSUE THREAD

**Issue by vinceprofeta** [Yomguithereal/baobab-react#132]
componentWillMount, getChildContext, componentWillReceiveProps will all be deprecated. 

Are there plans to release a version with the updated API's? 

It might be cool to use Hooks as well

**Comment by Yomguithereal** [comment]
I don't have much time right now but if you can draft some things to update the lib to support latest react updates it would be rad. I would also review hook-related prs.

**Comment by JosephClay** [comment]
Created a pull for this, see  #133

**Comment by vinceprofeta** [comment]
Closing issue with @JosephClay pull to support hooks
