### ISSUE TITLE
What's a good way to deal with deeply nested cursors?

### ISSUE THREAD

**Issue by bebraw** [Yomguithereal/baobab-react#17]
I have a tree like this:

```
const tree = new Baobab({
  lanes: []
}, {
  validate: {
    lanes: [{
      id: 'number',
      name: 'string',
      notes: [
        {
          id: 'number',
          task: 'string',
        }
      ]
    }]
  }
});
```

It is possible the tree will grow further as I add new concepts to the system (maybe boards etc.).

So far the decorator syntax has worked just fine. I feel it gets a little cumbersome on the lower levels of the hierarchy, though. To point at notes I would have to do something like this:

```javascript
@branch({
  cursors: function() {
    return {
      note: ['lanes', this.props.laneIndex, 'notes', this.props.noteIndex],
    };
  }
})
...
```

Maybe the cursor of previous level could be passed instead of root to the child instead? Then I could do:

```javascript
// XXX: this should point to lanes cursor, not root to work! Needs to be passed as a prop?
@branch({
  cursors: function() {
    return {
      note: ['notes', this.props.noteIndex],
    };
  }
})
...
```

If I could do this, I wouldn't have to care about the whole hierarchy, just the immediate parent.

How would you deal with deep nesting like this?

**Comment by Yomguithereal** [comment]
This is an interesting use case. I am think of a possibility to do something like this through props or context but need to think this a little bit more because cases when this would not be as simple. What you can do in the meantime is to pass the base of the path as a prop, for instance.

On a side note, you seem to be using `baobab@0.4.4` here whereas this repo deals with `baobab@1.0.0` version. There is a `baobab@1.0.0-rc1` available on npm and I will soon release v1.

**Comment by bebraw** [comment]
@Yomguithereal Cool. I'll go with props.

**Comment by bebraw** [comment]
@Yomguithereal I've been thinking this a bit more. It seems to me that in my case the smartest move would be to flatten the structure (notes and lanes and root level) and provide facets.

Related: https://github.com/Yomguithereal/baobab/issues/225.

**Comment by Yomguithereal** [comment]
I was thinking about this lately but I guess I'll see how cerebral fix the problem.

**Comment by bebraw** [comment]
@Yomguithereal Yeah, apparently monkeys solve this neatly. There's a [WIP demo](https://github.com/survivejs/cerebral-demo).

**Comment by Yomguithereal** [comment]
Cool. Will check this out asap.
