### ISSUE TITLE
Decorator for persisting data

### ISSUE THREAD

**Issue by bebraw** [Yomguithereal/baobab-react#18]
I set up a little snippet for persisting baobab data. Maybe you might want to include it to `baobab-react` after some refactoring (extract hoc etc.). Here it is:

```javascript
'use strict';
import React from 'react';

const root = (Component, tree, storage, storageName) => {
  return class Persist extends React.Component {
    constructor(props) {
      super(props);

      var data = storage.get(storageName);

      if(data) {
        tree.set(data);
        tree.commit();
      }

      window.addEventListener('beforeunload', function(e){
        storage.set(storageName, tree.get());
      }, false);
    }
    render() {
      return <Component {...this.props} {...this.state} />;
    }
  };
};

export default (tree, storage, storageName) => {
  // storage expects
  // * get(storageName)
  // * set(storageName, data)
  return (target) => root(target, tree, storage, storageName);
};
```

Usage:

```javascript
@persist(tree, storage, 'app')
@root(tree)
export default class App extends React.Component {
...
}
```

I'm not sure if the operation makes any sense elsewhere than tree level but it's nice to have it in a decorator. Nice and tidy.

**Comment by Yomguithereal** [comment]
This is an interesting decorator. I personally prefer to deal with the tree "hydration" elsewhere than in a component but I think this could be very useful to some. I won't add it to the library quite soon however since I want to consolidate the root/branches duo for every pattern before exploring the bonuses :).

**Comment by bebraw** [comment]
Yeah, it's a special case. I just wanted a quick and easy way to provide persistency for my demo. I suppose a proper decorator would take migrations in count (tree schema can change). You would have to be able to define those somehow.

Whole hydration thing is interesting. There are solutions like [react-resolver](https://github.com/ericclemmons/react-resolver) to get the initial data. I guess one way to solve it would be to push it away from components and hide it behind some kind of a store interface. I mean you would connect your components to stores and it would deal with synchronization automatically elsewhere.

**Comment by Yomguithereal** [comment]
There is also a project we are discussing with @christianalfoni and @jacomyal concerning an implementation on 'missing' parts of the tree. The idea is for the tree to notify you when a part of it is missing so you can trigger data fetching lazily etc.
