### ISSUE TITLE
Add check against non-array cursor selector for `@branch`

### ISSUE THREAD

**Issue by bebraw** [Yomguithereal/baobab-react#19]
If you pass something else than an array to `@branch`, it will yield `Uncaught TypeError: value.some is not a function`. It would be a good idea to check against this early on (`Array.isArray`?) and give warnings for failing selectors.

**Comment by Yomguithereal** [comment]
That's weird. I thought I covered this case already. It seems I missed something. I start investigating.

**Comment by Yomguithereal** [comment]
Wait, what do you mean by passing an array to `@branch`? You're supposed to pass an object to it.

**Comment by bebraw** [comment]
The situation was like this:

```javascript
@branch({
  cursors: function() {
    return {
      lane: ['lanes', this.props.index],
      something: {...} // -> crash because Object doesn't have `some`
    };
  }
})
...
```

**Comment by Yomguithereal** [comment]
Ok, thanks. I think baobab `1.0.1` should handle the problem thusly now: you can pass as a cursor anything you could pass as first arg to `.get` or `.select`. So your object will be considered as a descriptor object filtering an array and should not throw.

But I'll test that just to be sure.

**Comment by Yomguithereal** [comment]
This should now be fixed.
