### ISSUE TITLE
Article preview

### ISSUE THREAD

**Issue by christianalfoni** [Yomguithereal/baobab-react#35]
Hi there,

You can check out the article preview at: https://github.com/christianalfoni/EmptyBox/blob/master/posts/2015_04_26_Handling-complex-state-with-Baobab.md. Please let me know if you think I should take a different turn etc. But yeah, there it is :-)

It is not published yet btw.

**Comment by Yomguithereal** [comment]
Reviewing this today @christianalfoni.

**Comment by RJ** [comment]
good article! are you at all inclined to recommend a specific baobab-react method?

since i'm already babel'ed, i'm leaning towards es7 decorators, mainly because i like seeing the cursors/facets defined at the top of the file, above the class.

might be nice to give some guidance as to which baobab-react approach to take, since there are lots of options.

**Comment by Yomguithereal** [comment]
I guess the cool kids nowadays are the higher order component and the wrapper ones. I personally quite like the ES7 decorators for the reasons you state but the fact that the proposal is not fully accepted yet is a bit risky.

**Comment by Yomguithereal** [comment]
@christianalfoni, I added annotations to the commit :).

**Comment by christianalfoni** [comment]
@Yomguithereal Already committed fixes, thanks for taking the time :-)

I agree that decorators is the best approach really. 2 reasons:

1. You define the cursor/facets dependencies just above the component, not when you export the component (ES6 classes)

2. The state is exposed on the **props** object, which indicates it is external... which it actually is. **state** is more the internal state of the component... conceptually

Too bad they are not quite stable yet. Looking forward to it though :-)

When going through the patterns I do not really see the benefit of "wrappers". Though "data-wrapper-components" are a thing in React world, they do not work very well with Baobab I think. Mixins/higher-order does the job I think.

Or are there any arguments for having wrappers?

**Comment by christianalfoni** [comment]
@Yomguithereal btw, you feel ready for releasing an article on new version? I can hold on a bit longer if there is something you want to clean up etc. first :-)

Btw, I will also ensure that previous article has the updates.

**Comment by Yomguithereal** [comment]
Well I guess you can fire :-). The last two patches made the 1.0.0 version stable enough I think.

**Comment by christianalfoni** [comment]
Okay, cool, will put it out there then! :-)

**Comment by christianalfoni** [comment]
Its live: http://christianalfoni.com/articles/2015_04_26_Handling-complex-state-with-Baobab

**Comment by Yomguithereal** [comment]
I guess we can close this issue now :).
