### ISSUE TITLE
npm install causes error when bable is not installed globally

### ISSUE THREAD

**Issue by danawoodman** [Yomguithereal/baobab-react#36]
If babel is not available system wide, when installing via `npm install baobab-react`, I get the following error:

```bash
> babel ./src --out-dir dist-modules

sh: babel: command not found
```

I prefer not to install global modules if at all possible so don't have it available. Also, this will require production deployments to have babel available system wide. 

Is there perhaps a better way to have the ES6 files built that doesn't require local global dependencies?

**Comment by danawoodman** [comment]
That was strange, I guess it was actually related to upgrading from the git version to the npm version and not doing an `npm uninstall --save baobab-react`. Once I did that and reinstalled it everything worked. Sorry for false alarm

**Comment by Yomguithereal** [comment]
I'll check that on my side just to be sure once more.

**Comment by wzup** [comment]
Same error here.

`"babel-cli": "^6.3.17",`
window 8.1
npm 2.5.1
node v0.12.0

**Comment by KokoDoko** [comment]
Same error here:
npm install --save-dev babel-cli
babel script.js
-->error--> babel: command not found

**Comment by Yomguithereal** [comment]
This module currently uses babel v5, not v6. Having babel v6 installed globally messes this up?
