### ISSUE TITLE
Invariant violations with `cursors` when using decorators

### ISSUE THREAD

**Issue by bebraw** [Yomguithereal/baobab-react#37]
Even though I tried the example provided at the README, `cursors` contextType yields

```
Warning: Failed Context Types: Invariant Violation: Lane: context type `cursors` is invalid; it must be a function, usually from React.PropTypes. Check the render method of `ComposedComponent`.
```

Any idea what might cause that? I have [the full source](https://github.com/survivejs/webpack_react/tree/7aa964885b630d94d36d018844631fbdd29fbb1c) available.

It would be enough for my purposes if it was possible to access the cursors via props (`props.cursors`) but there might have been some reason why this cannot work.

**Comment by Yomguithereal** [comment]
This is weird. Could you point towards your precise file?

**Comment by bebraw** [comment]
Sure. [Lane](https://github.com/survivejs/webpack_react/blob/7aa964885b630d94d36d018844631fbdd29fbb1c/project_source/07_from_notes_to_kanban/kanban_app/app/components/Lane.jsx), [Notes](https://github.com/survivejs/webpack_react/blob/7aa964885b630d94d36d018844631fbdd29fbb1c/project_source/07_from_notes_to_kanban/kanban_app/app/components/Notes.jsx).

**Comment by Yomguithereal** [comment]
[Here](https://github.com/survivejs/webpack_react/blob/7aa964885b630d94d36d018844631fbdd29fbb1c/project_source/07_from_notes_to_kanban/kanban_app/app/components/Lane.jsx#L18) : you wrote `cursor` instead of `cursors`.

[Here](https://github.com/survivejs/webpack_react/blob/7aa964885b630d94d36d018844631fbdd29fbb1c/project_source/07_from_notes_to_kanban/kanban_app/app/components/Lane.jsx#L11) : you are using `this.props` but we changed that before `0.1.0` release to `function(props, context)` so we could adapt to props changes more efficiently.

**Comment by Yomguithereal** [comment]
[Here](https://github.com/survivejs/webpack_react/blob/7aa964885b630d94d36d018844631fbdd29fbb1c/project_source/07_from_notes_to_kanban/kanban_app/app/components/Notes.jsx#L20) : idem for the singular `cursor`.

**Comment by Yomguithereal** [comment]
But I notice I wrote the singular in the documentation. Which is not very clever of me...

**Comment by bebraw** [comment]
> Here : idem for the singular cursor.

Great, that fixed it.

> Here : you are using this.props but we changed that before 0.1.0 release to function(props, context) so we could adapt to props changes more efficiently.

You mean something like?

```
@branch({
  cursors: function(props, context) {
    console.log('props', props, 'context', context);

    return {
      // XXX: this should be just [props.index] - maybe props.parent.concat[props.index]
      lane: ['lanes', props.index],
    };
  }
})
```

Why are `props` and `context` undefined, though? I suppose I'm not using it quite right yet.

**Comment by Yomguithereal** [comment]
Well that's strange indeed. Can you make sure you are using at least `baobab@v1.0.2`?

**Comment by bebraw** [comment]
> Well that's strange indeed. Can you make sure you are using at least baobab@v1.0.2?

Yeah, that was it.

`context` would be a lot more useful if I had immediate parent branch there instead of just `tree`.

**Comment by bebraw** [comment]
Another strange thing. Looks like `this.context` is undefined at constructor. It is accessible at `render`, though. See [Notes](https://github.com/survivejs/webpack_react/blob/137a64fb176b13c1891e5bad664e4c1558079d34/project_source/07_from_notes_to_kanban/kanban_app/app/components/Notes.jsx).

I can work around this by passing the parent branch reference through a prop, though.

**Comment by Yomguithereal** [comment]
Yes, `this.context` is undefined in constructor, but the constructor function takes two arguments in React, props and context `constructor(props, context)`.

**Comment by bebraw** [comment]
> Yes, this.context is undefined in constructor, but the constructor function takes two arguments in React, props and context constructor(props, context).

Ok, great! Now I wish React would use the same convention for `render` as well... Maybe one day.

Apart from #17 (cursor nesting) the React wrapper is starting to look very good for my usage. :)

**Comment by Yomguithereal** [comment]
Is the

```js
@branch({
  cursors: function(props, context) {
    console.log('props', props, 'context', context);

    return {
      // XXX: this should be just [props.index] - maybe props.parent.concat[props.index]
      lane: ['lanes', props.index],
    };
  }
})
```

bug fixed then?

**Comment by bebraw** [comment]
Yeah, that did the trick.

As you can see I would love to write `[props.index]` to keep the declaration separate from context but that's another issue.

**Comment by Yomguithereal** [comment]
What you can do also is to pass a cursor directly:

```js
@branch({
  cursors: function(props, context) {
    return {
      lane: props.laneCursor,
    };
  }
})
```

**Comment by bebraw** [comment]
> What you can do also is to pass a cursor directly: ...

This works, yup.

If we go this route, why not to just skip decorator and pass an actual cursor directly? Design-wise it could be nice to keep cursors separate from actual components and decorators/hocs/... achieve this effectively, though,
