### ISSUE TITLE
Using in Sinatra / Rails

### ISSUE THREAD

**Issue by Johnius** [Yomguithereal/baobab-react#40]
How should I compile the library to use it as a standalone static js file?

**Comment by Yomguithereal** [comment]
What is your workflow with React in your app? Do you use jsx? Do you use browserify, webpack, babel?

**Comment by Johnius** [comment]
I'm using Sinatra with gems coffee-script & coffee-react (it's a JSX compiler for coffeescript).
And I'm explicitly compiling JSX Coffeescript to Coffeescript and then to JS.
```ruby
  get '/js/react/*.js' do
    filename = [params[:splat]].flatten.join.split('.').slice(0)

    coffee (CoffeeReact.transform File.open("client/js/react/#{filename}.coffee"))
  end
```

I'm pretty sure that I need to use something like browserify but with gulp/grunt/etc.

**Comment by psawaya** [comment]
I'd also appreciate a static standalone version of this.

**Comment by Johnius** [comment]
I just pull-requested the gulp script for compiling standalone version of BaobabReact.mixins. #42

**Comment by Yomguithereal** [comment]
I've added `npm run build` to build the files. Is this needed to build them as browserify standalones? If yes, what name you I give them?

**Comment by Johnius** [comment]
I use mixins through global variables. Such as this:
* BaobabReactMixins.root
* BaobabReactMixins.branch

I think we need to add support of choosing global variable name. Through arguments for example.
