### ISSUE TITLE
Suggestion to have Facet constructors instead

### ISSUE THREAD

**Issue by christianalfoni** [Yomguithereal/baobab-react#44]
Hi @Yomguithereal !

I got some feedback on the article I wrote: [Handling complex state with Baobab](http://www.christianalfoni.com/articles/2015_04_26_Handling-complex-state-with-Baobab) and it led me to think of something. As suggested in the article a really powerful concept with facets is to let it have its own "one way flow" with the tree, allowing it to load data when you try to grab non existing data:

![screen shot 2015-05-02 at 13 03 22](https://cloud.githubusercontent.com/assets/3956929/7440825/a5eaebf4-f0cb-11e4-9c8d-49b315385a7d.png)

But the current setup with facets quickly creates circular dependencies. So looking at the above image:

1. The **tree** have to depend on the **facet** as it needs to be defined with the tree
2. The **facet** depends on the **loader**
3. The **loader** depends on the **tree**
4. *Bipeti-bapeti-bo*, circular dependency

So what I suggest is completely separating facets from the tree. This would be the syntax:

*MyFacet.js*
```js
import tree from './tree.js';

let MyFacet = tree.createFacet({
  cursors: {},
  get() {}
});

export default MyFacet;
```

*Component.js*
```js
import React from 'react';
import MyFacet from './MyFacet.js';

let Component = React.createClass({
  facets: {
    foo: MyFacet
  },
  ...
});
```

Come to think of it... would this actually work? Have not tested it, but letting the issue stay as it is an important thing I believe :-) Should be documented.

**Comment by Yomguithereal** [comment]
This code should actually already work. I did not document it yet because I needed to be able to change the internal API and this would mean breaking changes if people were to use it themselves.

**Comment by christianalfoni** [comment]
I have been thinking some more @Yomguithereal ...

The approach above is not ideal thinking isomorphic, as it will bring in the tree instance. I am thinking a lot about trying to find the best way solving isomorphism and though there are lot of thoughts, one of them I think is important nevertheless. **Be able to access the tree instance inside the facet**.

*selectedProjectFacet.js*
```js
import projectLoader from './projectLoader.js';

let selectedProjectFacet = {
  cursors: {
    id: ['selectedProjectId'],
    projects: ['projects']
  },
  get(state, tree) {
    return state.projects[state.id] || projectLoader(tree, state.id);
  }
};

export default selectedProjectFacet;
```

The facet should not be restricted to only grab data from the cursors defined, they should be able to grab any data from the tree. This also makes sure that any dependencies to the facet, whatever they might be, will operate on the instance of the tree the facet is running on. In other words, it is more decoupled.

**Comment by Yomguithereal** [comment]
Initially, we decided not to enable tree access in facets with @jacomyal for the following reason: we did not want people to be able to grab data from the tree while not specifying correctly their cursors dependencies and be in a false impression that the facets would update correctly if doing so.

I guess that binding the get function to the tree and access it through `this` might remain a possibility but we need to discuss that.

On a side note, are the facets the correct place to trigger data fetching and so on?

Wouldn't the `select/missing/cursor` [hook](https://github.com/Yomguithereal/baobab/issues/188) be more appropriate?

**Comment by christianalfoni** [comment]
Yeah, I agree it is a concern of accessing the tree when you should do it through a cursor. It is possible to just call a Facet as a function, creating a closure for the passed tree and return the facet. But it is a lot of syntax, compared to having access to the tree in the facet.

I am not such a big fan of "helping the developer by restricting", as it means that the developer does not understand what the tool does. If the developer does not understand the difference using a cursor and grabbing state directly from the tree, the developer is not familiar enough with the tool I think. And actually solving the issue would make them more enlightened regarding the difference of a cursor and the tree. In summary exposing the tree opens up for new patterns and a good, and important, learning experience if you get it wrong :-)

Good question on correct place to load missing data... hm. What I like about facets is that you can return data that will not be put into the tree. For example if a project is missing in the tree you can return a temporary object from the facet that will not be injected into the tree. An event would have to put the data into the tree.

An other point is that with the `select/missing/cursor` event you would actually have to `select` the data to make it trigger:

So:

```js
import projectLoader from './projectLoader.js';

let selectedProjectFacet = {
  cursors: {
    id: ['selectedProjectId'],
    projects: ['projects']
  },
  get(state, tree) {
    return state.projects[state.id]; // This would not trigger any event
  }
};

export default selectedProjectFacet;
```

The last challenge I see using events to handle missing data is that it is global. Maybe different facets wanted to handle missing data differently, that is not possible with one event.

So yeah, as of now I think the correct place to handle missing data is inside a facet. It is based on theories and testing, no large production application, but it makes a lot of sense. Facebook also mentioned in the flux-conf Q&A that they grabbed missing data in their store getters, so it is not an unfamiliar concept.

I acknowledge the concern, but I think a restriction to the tree does more harm than good. It does not just restrict developers doing mistakes, but it also restricts evolving new patterns and restricts developers being put in a situation where they will learn something very valuable about Baobab if they do it wrong :-)
