### ISSUE TITLE
no dist-modules ?

### ISSUE THREAD

**Issue by larryhengl** [Yomguithereal/baobab-react#45]
Hey Gang, really enjoying baobab.  Was using it for the past week in a project.  Just did an npm update on (baobab, baobab-react) and now I'm getting a new error:
Error: module "./dist-modules/mixins.js" not found from "/..../node_modules/baobab-react/mixins.js"

Previously I followed the wiki page and simply did:
npm i baobab-react --save
and then in a react component:
var mixin = require('baobab-react/mixins').branch; ...
and it worked nicely.

Can't get the project to start now.

Am I missing a step here?

Thanks, and great work!

:Larry

**Comment by Yomguithereal** [comment]
Try to delete your npm dependencies and reinstall them. If you upgraded from the pre-release version to the 0.1.0 it's possible you can get this kind of error.

Something along:

```
rm -rf node_modules
npm install
```

Tell me whether this fixes your issue.

**Comment by larryhengl** [comment]
Thanks @Yomguithereal, but that didn't fix it.  I rm'd the baobab-react folder and reinstalled.  The js files (mixins.js, etc) all live next to index.js.  but index.js requires them in from ./dist-modules, and that folder does not exist.

**Comment by larryhengl** [comment]
the only way i got this to work was to pull down the repo and build it with your `prepublish` script,
then copy the dist-modules folder from there over to my projects node_modules/baobab-react folder.

**Comment by Yomguithereal** [comment]
I am a bit puzzled here @larryhengl. If I run `npm i baobab-react --save`, I get the `dist-modules` folder and the module works without further ado. What is your version of npm? Is the project you are working on hosted on github perchance so I can check whether there is an uncovered edge case here?

**Comment by larryhengl** [comment]
@Yomguithereal , yeah it's odd.  in a completely new dir the install works as you describe - includes dist-modules and the other deps: baobab & react.  But when I install it from within my project folder I don't get all of it.  The existing dir already had react and baobab, and a previous baobab-react install.  
npm -v   is 2.7.4
maybe a caching issue?
not sure if this helps but the package.json files differ slightly after the two different installs. Differences noted below.

in-project package.json has:
```javascript
"gitHead": "38db32a5975787615fa3ea869628a8d0816b8812",
  "readme": <snipped, too long for this post>,
  "readmeFilename": "README.md",
  "_id": "baobab-react@0.1.0",
  "_shasum": "beab4a2a249023a81e683f0dcf707c4bef4c6633",
  "_from": "git://github.com/Yomguithereal/baobab-react.git",
  "_resolved": "git://github.com/Yomguithereal/baobab-react.git#38db32a5975787615fa3ea869628a8d0816b8812",
  "_fromGithub": true
```
standalone install has:
```javascript
"gitHead": "7c4b7e4d94e61480d82c84523e77cf89f3efed8a",
  "_id": "baobab-react@0.1.0",
  "_shasum": "e29abcc0c38448cb7550742c01a1a2844b8bc645",
  "_from": "baobab-react@*",
  "_npmVersion": "2.7.4",
  "_nodeVersion": "0.12.2",
  "_npmUser": {
    "name": "yomguithereal",
    "email": "kropotkinepiotr@gmail.com"
  },
  "maintainers": [
    {
      "name": "yomguithereal",
      "email": "kropotkinepiotr@gmail.com"
    }
  ],
  "dist": {
    "shasum": "e29abcc0c38448cb7550742c01a1a2844b8bc645",
    "tarball": "http://registry.npmjs.org/baobab-react/-/baobab-react-0.1.0.tgz"
  },
  "directories": {},
  "_resolved": "https://registry.npmjs.org/baobab-react/-/baobab-react-0.1.0.tgz"
```

**Comment by bebraw** [comment]
That `38db32a5` hash is pointing at the last commit at this repository. Is it possible your project is pointing at this repository instead of NPM? If it does, `dist-modules` will be missing as it gets generated by the `prepublish` script.

You could try removing `baobab-react` line from your `package.json` before hitting `npm i baobab-react --save`.

**Comment by Yomguithereal** [comment]
Yes, @bebraw is right, it seem you are pulling the `baobab-react` module from git itself rather than npm. If this is a cache issue, you can always try `npm cache clear` (might require sudo).

**Comment by larryhengl** [comment]
@bebraw was right indeed.  somehow the baobab-react entry in my project's package.json snuck in a ref to the github repo rather than going thru the npm registry.  removing that entry and the corresponding node_modules folder, then reinstalling did the trick.  thanks guys.  will close this.
