### ISSUE TITLE
Uncaught Error: baobab.Facet.refresh: first argument should be an array.

### ISSUE THREAD

**Issue by tokenvolt** [Yomguithereal/baobab-react#47]
I'm not sure if this is related to baobab-react (maybe baobab itself) or I'm doing something incorrectly, but I keep getting this error if I use mixins.

Here is the full stacktrace:
![image](https://cloud.githubusercontent.com/assets/1728072/7472861/4d0421f6-f33f-11e4-8f6e-876a45406aee.png)

baobab 1.0.3, baobab-react 0.1.0
I don't get this error if I use baobab 1.0.1.

I can make a test app reproducing the issue, if it's necessary.

**Comment by Yomguithereal** [comment]
Hello @tokenvolt,
I will need some code to see what's wrong. But, with what you provide, I guess this should come from a `cursors` mapping passed as a function and react upon props change. But this is indeed probably a bug.

**Comment by tokenvolt** [comment]
@Yomguithereal Okay, I will make a test app to reproduce it during this week when I have a time.

**Comment by Yomguithereal** [comment]
Any news about this @tokenvolt?

**Comment by tokenvolt** [comment]
Hello @Yomguithereal. Here is the app https://github.com/tokenvolt/baobab-react-issue-47, but I think this was fixed in 0.1.1, because I don't encounter it with that version.
