### ISSUE TITLE
Uncaught TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by ambidexterich** [Yomguithereal/baobab-react#49]
This could very well be me doing something wrong...When I unset a cursor that is a leaf off of another cursor, the render method is improperly updating the components so that the removed item gets removed from the DOM but items don't shift properly. Also, once the item is removed, I get the error mentioned in the title. I've found ways around the rerender issue but have come up empty on the error.

I created a fiddle that demostrates the issue I am running into. Any insight would be great.
http://jsfiddle.net/6tfv2016/5/

**Comment by ambidexterich** [comment]
To summarize the code fiddle: if I have AppComponent > SectionComponent (UL) > ListComponentCollectionItem (LI) and I remove one of the ListComponentCollection items using ListComponentCollectionItem cursor.unset()  I get the error. However if I generate the list in SectionComponent by looping through the collection and rendering the LI directly without the extra component I do not receive the error when I remove an item.

**Comment by Yomguithereal** [comment]
Hello @ambidexterich, sorry for the late answer. I need to investigate your example to see what went wrong.
