### ISSUE TITLE
React router obscuring source of facet error

### ISSUE THREAD

**Issue by tnrich** [Yomguithereal/baobab-react#51]
So I am creating a facet on my baobab tree in the normal way, and am trying to use the facet in a react component via the react-baobab mixin. There is an error in the code (that I wrote) that the facet is calling in its get method, but instead of displaying a helpful error, or allowing me to break on the actual error, the event isn't caught until it has bubbled up to an error handler in the react-router code. 

This is making debugging the source of the error very difficult... I am not sure quite what to do. Does anyone have an idea of what could be done differently to allow normal error handling to occur? 

One thing I'm doing right now, but don't think should be the final solution, is calling the facet.get() method independent of the react router, right after I make the tree. 
 
I've attached some screenshots of what the error looks like. 

![image](https://cloud.githubusercontent.com/assets/2730609/7640438/1f73c57a-fa38-11e4-8fbb-0d3846cfeb9c.png)

![image](https://cloud.githubusercontent.com/assets/2730609/7640446/29776414-fa38-11e4-97dd-d6dd19b1f105.png)

Feel free to ask any clarifying questions if you have them and thanks in advance!

**Comment by tnrich** [comment]
Also, this might be more of an issue with react router than with baobab.. sorry if I'm polluting the baobab issue space.

**Comment by tnrich** [comment]
Yup, I don't think it is the facet's fault at all. I'm not sure why it is occurring just since I've put in the facet code, but it is definitely a known react-router issue:
https://github.com/rackt/react-router/issues/946

**Comment by Yomguithereal** [comment]
Hello @tnrich. Did you discover more things? Should I try and change things to improve error bubbling in this use case?

**Comment by tnrich** [comment]
Hey @Yomguithereal , it is definitely react-router's fault. It just happened to occur when I started using facets and wasn't using them quite right and was running into errors. This can be closed I think.
