### ISSUE TITLE
Warning: Failed Context Types: prop type `tree` is invalid; it must be a Baobab tree.

### ISSUE THREAD

**Issue by y4ku** [Yomguithereal/baobab-react#53]
These are the only places that I am attempting to use the tree.
Any thoughts?

var Baobab = require('baobab');

**State Tree File:**
```
var ScheduleStateTree = new Baobab({
	model: {
	},
	view: {
		current: 'day'
	}
});

module.exports = ScheduleStateTree;
```

**Schedule Component:**
```
var React = require('react');
var Router = require('react-router');
var { Link } = Router;
var ScheduleContainer = require('./Schedule/ScheduleContainer');
var ScheduleStateTree = require('./../StateTrees/ScheduleStateTree');
var BoababReactMixinRoot = require('baobab-react/mixins').root;

var Schedule = React.createClass({
    mixins: [BoababReactMixinRoot],
    render: function() {
        return (
            <div className="schedule">
                <h2>Schedule</h2>
                <ScheduleContainer tree={ScheduleStateTree} />
            </div>
        );
    }
});

module.exports = Schedule;
```

**Container Component:**
```
var React = require('react');
var Router = require('react-router');
var { Link } = Router;
var ScheduleToggle = require('./ScheduleToggle');
var BoababReactMixinBranch = require('baobab-react/mixins').branch;

var ScheduleContainer = React.createClass({
	mixins: [BoababReactMixinBranch],
    render: function() {
        return (
        	<div className="schedule-container">
        	
        	</div>
        );
    }
});

module.exports = ScheduleContainer;
```

I keep getting the following:
Warning: Failed propType: prop type `tree` is invalid; it must be a Baobab tree. Check the render method of `RouteHandler`.
app.js:25374 Warning: Failed Context Types: prop type `tree` is invalid; it must be a Baobab tree. Check the render method of `RouteHandler`.
app.js:25374 Warning: Failed Context Types: prop type `tree` is invalid; it must be a Baobab tree. Check the render method of `Schedule`.

**Comment by y4ku** [comment]
I did some more reading through the issue and eventually "hacked" the tree in so I could use it in ScheduleContainer: 
```
var Schedule = React.createClass({
    childContextTypes: {
         tree: PropTypes.baobab
    },
    getChildContext() {
        return {
            tree: ScheduleStateTree
        };
    },
    render: function() {
        return (
            <div className="schedule">
                <h2>Schedule</h2>
                <ScheduleContainer />
            </div>
        );
    }
});
```
The reason I don't have a wrapper component for schedule is because it is a top level route handler in React-Router.

I'm trying new things here like using smaller trees for the different routes where this kind of use case would be ideal.

**Comment by Yomguithereal** [comment]
Hello @y4ku, there are some issues like #25, discussing integration with `react-router`.

If you are trying to use a different tree per route, I guess you can have several different `root` component and then the `branch` one will adapt. Indeed, the `root` mixin/etc. does not do anything else than rooting the tree into the target component's context.
