### ISSUE TITLE
Branching components like in Baobab pre-v1

### ISSUE THREAD

**Issue by jacomyal** [Yomguithereal/baobab-react#57]
I have a pretty specific usecase where I actually would prefer to use the mixin exported from Baobab as it was [before the v1.0.0 release](https://github.com/Yomguithereal/baobab/tree/0.4.4#react-mixins) than any of the currently available implemented paradigms.

It would be great if this way of branching React components to a given tree was still available somehow. It could be something like:

```javascript
var mixinFactory = require('baobab-react/factory');

var Component = React.createClass({
  mixins: [ mixinFactory(myBaobabTree) ],
  cursors: { myCursor: [ 'my', 'path' ] },
  // ...
});
```

**Comment by Yomguithereal** [comment]
Muhahahaha.
