### ISSUE TITLE
Using with React Native

### ISSUE THREAD

**Issue by Shuangzuan** [Yomguithereal/baobab-react#58]
Here is my code:

```javascript
'use strict';

var React = require('react-native');
var {
  AppRegistry,
  StyleSheet,
  Text,
  View,
} = React;

var Baobab = require('baobab');
var mixins = require('baobab-react/mixins');

var stateTree = new Baobab({
  admin: {
    notifications: {
      list: []
    }
  },
  home: {
    feeds: []
  }
});

var AwesomeProject = React.createClass({
  mixins: [mixins.root],
  componentDidMount: function() {
    // console.log(this.state.cursors.notifications.length);
  },
  render: function() {
    return (
      <View tree={stateTree}>

      </View>
    );
  }
});

AppRegistry.registerComponent('AwesomeProject', () => AwesomeProject);
```

Here is the console log:

```
2015-06-03 14:36:45.004 [warn][tid:com.facebook.React.JavaScript] "Warning: Failed propType: prop type `tree` is invalid; it must be a Baobab tree."
2015-06-03 14:36:45.007 [warn][tid:com.facebook.React.JavaScript] "Warning: Failed Context Types: prop type `tree` is invalid; it must be a Baobab tree."
2015-06-03 14:36:45.008 [warn][tid:com.facebook.React.JavaScript] "Warning: Failed Context Types: prop type `tree` is invalid; it must be a Baobab tree."
```

I am not understand that the README say `With mixins, you need to pass your tree through props` mean. Need your help. Thanks.

**Comment by Yomguithereal** [comment]
Hello @Shuangzuan.
You should pass the tree as a prop to the `AwesomeProject` component, not the `View` one. Or else you should apply the root mixin to the `View` component if you'd rather root the tree from it.

**Comment by Shuangzuan** [comment]
Thanks @Yomguithereal 
I don't know how to pass the tree prop to `AwesomeProject` component, because of in `React Native` I need call 

```javascript
AppRegistry.registerComponent('AwesomeProject', () => AwesomeProject);
```

And the signiture of this function is

```javascript
`registerComponent: function(appKey: string, getComponentFunc: Function): string`
```

The first parameter should be a `appKey` string. So I don't know how to do like this

```javascript
React.render(<Application tree={tree} />, mountNode);
```

**Comment by Yomguithereal** [comment]
Hello @Shuangzuan. I cannot find a way either to pass props to the component you pass to `registerComponent`. What you should do then is to apply the root mixin to your `View` component. If the `View` component needs to access cursor's data itself, then you'll either need to create a wrapper component to root the tree or pass the tree through context from the `Application` one and I'll show you how if you need to and if we must come to that.

**Comment by ldesplat** [comment]
Adjusted from my codebase which uses react native.
```
var BackyardApp = React.createClass({
    mixins: [branch],

    render: function () {
        ...
    }
});

var AppWrapper = React.createClass({
    mixins: [root],

    render: function () {

        return (
            <App></App>
        );
    }
});

var AppWrapperWrapper = React.createClass({
    render: function () {
        return <AppWrapper tree={Tree} />;
    }
});

AppRegistry.registerComponent('backyard', () => AppWrapperWrapper);
```

**Comment by Yomguithereal** [comment]
Seems like a sensible solution @ldesplat. Do you know the reason why you cannot pass props to the root component in `react-native` by the way?

**Comment by Shuangzuan** [comment]
Thank you @ldesplat @Yomguithereal.
It works!
