### ISSUE TITLE
peerDependencies and react-native

### ISSUE THREAD

**Issue by ldesplat** [Yomguithereal/baobab-react#59]
Hi,

This is mostly annoying more than anything but since there is a peerDependency to react 0.13+, whenever I do npm install it installs react. But I already have react-native and I don't need react installed.

I don't really know how to resolve this. I don't see anything from NPM which would allow us to OR a peer dependency. I see 2 solutions:
1) Remove the peerDependency on react
2) Publish a 2nd package which has peerDependency on react-native and npm publish it as baobab-react-native?

Cheers,
Lois.

**Comment by Yomguithereal** [comment]
Hello @ldesplat,
This is indeed an interesting problem and both solutions feel somewhat frustrating. Do you happen to know other projects that would have stumbled upon the same issue? Maybe they have a solution.

**Comment by Yomguithereal** [comment]
Seems there are some discussions about peer dependencies behavior for npm v3 [here](https://github.com/npm/npm/issues/6565).

**Comment by ldesplat** [comment]
I found other libraries just removed or never had the peerDependencies.
Thanks for finding those discussions. The good thing is that npm@3 at least won't install by default. 

I could not find anything related to our problem in the issues in NPM so I created a new issue discussing a potential fix: https://github.com/npm/npm/issues/8478 . Hopefully some good feedback will come out of it or some existing solutions :)

**Comment by Yomguithereal** [comment]
We'll see what emerges from this indeed. I will probably go with solution n°1 soon so this does not become a problem for `react-native` user. Solution n°2 is overkill I think.

**Comment by Yomguithereal** [comment]
On a side note, I struggle to find another library than `react` and `react-native` that would need an `OR` system for peer dependencies.

**Comment by Yomguithereal** [comment]
There are no peerDeps anymore in the lib.
