### ISSUE TITLE
Composed component are out of context

### ISSUE THREAD

**Issue by Yomguithereal** [Yomguithereal/baobab-react#61]

**Comment by cocodrino** [comment]
hi @Yomguithereal , I've facing a similar problem, I'm trying use https://github.com/FormidableLabs/react-shuffle but the nested children doesnt receive the context, this issue seems will be solved in react 14 but I wish to know  if there is some trick for this, thanks!

**Comment by Yomguithereal** [comment]
Hello @cocodrino. This problem arise because React does not propagate context when you render `this.props.children`. If you can modify the part where `this.props.children` is used then you can use the solution described in #52. Else, I fear this might be difficult to overcome this without `0.14`.

**Comment by Yomguithereal** [comment]
This should be fixed by `react@0.14.0-rc1`.
