### ISSUE TITLE
Concerning Baobab v2 evolutions for the react integration

### ISSUE THREAD

**Issue by Yomguithereal** [Yomguithereal/baobab-react#66]
`baobab-react` will probably not evolve much in a conceptual way with the release of Baobab v2. The main evolutions should be the overall simplification of the bindings by dropping the `facets` key since the API has been harmonized: data & computed data now share the same methods:

```js
// mixins
React.createClass({
  mixins: [branch],
  cursors: {} // no more 'facets' key
});

// Higher order etc.
branch(Component, {
  data: ['data']
});

// Instead of
branch(Component, {
  cursors: {
    data: ['data']
  }
})
```

**Comment by marbemac** [comment]
Looks great to me.

**Comment by tnrich** [comment]
hey @Yomguithereal , do you know when you expect baobab-react to work with the v2 version of baobab?

**Comment by Yomguithereal** [comment]
Hopefully, very soon.

**Comment by tnrich** [comment]
Cool beans! Thanks @yomguithereal!

**Comment by Yomguithereal** [comment]
The dev version of `baobab-react` working with v2 is now available through:

```bash
npm install baobab-react@dev
```

**Comment by tnrich** [comment]
Awesome thanks @yomguithereal , I'll be trying it out soon

**Comment by bfitch** [comment]
Anyone had success working with v2?

package.json:
```
    "baobab": "^2.0.0-dev9",
    "baobab-react": "^1.0.0-dev"
```

But am getting this error while building with webpack:

stdout:
```
ERROR in ./~/baobab-react/decorators.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./dist-modules/decorators.js in /Users/brian/projects/react-starter/node_modules/baobab-react
 @ ./~/baobab-react/decorators.js 1:17-56

ERROR in ./app/state.js
Module not found: Error: Cannot resolve module 'baobab' in /Users/brian/projects/react-starter/app
 @ ./app/state.js 11:14-31
```

Excited to try v2!

**Comment by tnrich** [comment]
I'm not having much luck getting it to work either, but for a different reason: 

```
Uncaught TypeError: Cannot read property '_computedDataIndex' of undefined(anonymous function) 
@ cursor.js:229_getComparedPaths 
@ cursor.js:222Cursor._updateHandler 
@ cursor.js:164Emitter.emit 
@ emmett.js:445commit 
@ baobab.js:369(anonymous function) @ baobab.js:316
```

![image](https://cloud.githubusercontent.com/assets/2730609/8769530/34af9842-2e54-11e5-86fe-d17f12436b8b.png)

I'm not quite sure what it causing it and it mysteriously doesn't seem to be thrown every time I reload the page.

**Comment by tnrich** [comment]
Whoops my above comment really only applies to baobab, not baobab-react. I'll repost it there.

**Comment by Yomguithereal** [comment]
@bfitch, I cannot reproduce your bug. Is your app open sourced somewhere so I can assess the problem?

**Comment by bfitch** [comment]
@Yomguithereal: here is my little react-baobab boilerplate repo: https://github.com/bfitch/react-starter/tree/baobab-v2. Checkout the `baobab-v2` branch then `npm run start` (which runs webpack). You should be able to observe the error above.

Thanks for looking into this. :)

**Comment by Yomguithereal** [comment]
So I cloned your repo, went to the `baobab-v2` branch then ran `npm install` then `npm run start` and I did not have any webpack errors. On which OS are you?

**Comment by bfitch** [comment]
OS X 10.9.5
node v0.10.38
npm 1.4.28

**Comment by bfitch** [comment]
I guess my node and npm versions are pretty out of date. Let me try to update those. I'll report back with any info.

**Comment by bfitch** [comment]
Updated to latest node and npm. Still no luck:
```
node -v
v0.12.7

npm -v
2.11.3
```

**Comment by Yomguithereal** [comment]
Just tried on OSX and still cannot reproduce the issue.

**Comment by ivan-kleshnin** [comment]
Works for me https://gist.github.com/ivan-kleshnin/feae0d67614b98752a95

**Comment by bfitch** [comment]
@Yomguithereal thanks again for looking into this. It seems it must be a problem unique to my environment, so everyone else carry on!

**Comment by saulshanabrook** [comment]
@bfitch I would try it in a docker container using the [`node` image](https://registry.hub.docker.com/_/node/).
