### ISSUE TITLE
noob here: changes in the latest release are confusing me

### ISSUE THREAD

**Issue by cocodrino** [Yomguithereal/baobab-react#70]
Hi, sorry but I'm very newbie with baobab and I'm trying to follow this article

http://christianalfoni.github.io/javascript/2015/02/06/plant-a-baobab-tree-in-your-flux-application.html

here christian create a tree stateTree and then use a mixing mixins: [stateTree.mixin]

```js


var MyComponent = React.createClass({
  mixins: [stateTree.mixin],
  cursors: {
    notifications: ['admin', 'notifications', 'list'],
    feeds: ['home', 'feeds']
  },
  renderFeed: function (feed) {
    return (
      <li>{feed.title}</li>
    );
  },
  render: function () {
    return (
      <div>
        <div>You have {this.state.cursors.notifications.length} notifiations</div>
        <ul>
          {this.state.cursors.feeds.map(this.renderFeed)}
        </ul>
      </div>
    );
  }
});
```

this is great, but now I'm notice in the readme than baobab-react requires a root and branches, why if I only need pass my tree to 1 component and dont need  branches?...

2) this line is causing me problems because I get a null mixin
var mixins = require('baobab-react/mixins')

I'm using webpack with babel compiler...
thanks!

**Comment by Yomguithereal** [comment]
Hello @cocodrino While this article is very good and well-written, it has become a bit outdated concerning react integration. Now you cannot use `tree.mixin` anymore. The reason of this is that one wouldn't tie his/her components' code to a specific instance of the tree. This is the reason why the Baobab tree is now passed to components through context.

This means you need to "root" one of your top-level components by using the `root` mixin and by giving it your tree as prop.

Then other components of your apps may "branch" themselves to the tree automatically.

There is a full example of this [here](https://github.com/Yomguithereal/baobab-react/blob/v2/docs/mixins.md) that I am currently writing for the new docs of the lib.

2) the `mixins` variable should be an object with two keys: `root` and `branches`. If this is not the case, then we have a problem and I can help you investigate if you can show me more of your code.

**Comment by cocodrino** [comment]
thanks @Yomguithereal , I suppose than this change simplify build isomorphic apps too...now I've a small doubt, if I need create 2 independents components, for instance the facebook chat for one side and the facebook updates in the other, is good approach build 2 root components and pass the same baobab structure? or maybe must I use 2 differents baobab objects?...thanks!

**Comment by Yomguithereal** [comment]
Do you mean you have different React roots in your application? If this is the case, just pass the same baobab object to both roots. But typically, people only have one root like an `<App />` component an root this one so that any descending component may branch itself.

**Comment by cocodrino** [comment]
thanks @Yomguithereal  I know than it seems a bit away of react's ideas but in my particular situation I think than is better idea keep two components with different mounting points in the html because it wasnt developed with react originally..I'll give it a try...thanks!.

**Comment by Yomguithereal** [comment]
If you have several react roots then yes, you should keep only one tree and pass it to all your roots I think. We were thinking of enabling the root mixin etc. to work as branch also for convenience and so those cases remain easy. Because I am sure having to root a component is not that ideal for your case.
