### ISSUE TITLE
[v2] basic action layer

### ISSUE THREAD

**Issue by Yomguithereal** [Yomguithereal/baobab-react#72]

**Comment by chcokr** [comment]
Hi, I'm wondering where this is documented?

**Comment by Yomguithereal** [comment]
Hello @chcokr. Right [here](https://github.com/Yomguithereal/baobab-react/blob/master/docs/higher-order.md#actions) for higher-order pattern. The same explanation also exists for other patterns.

**Comment by Yomguithereal** [comment]
As for hot-reload, just using react-transform should work without further ado.
