### ISSUE TITLE
Branch mixin does not update this.cursors and this.facets in componentWillReceiveProps

### ISSUE THREAD

**Issue by davidtinker** [Yomguithereal/baobab-react#75]
This causes problems with components using cursor paths with properties in them when they attempt to change the data via this.cursors.

    cursors: function(props) {
        return {data: ['views', 'users', props.user.id, 'balance']};
    },

Elsewhere:

    this.cursors.data.set(data);

Once properties have changed this.cursors will point at the wrong set of cursors.

The fix in mixins.js is simple:

    componentWillReceiveProps: function componentWillReceiveProps(props) {
        if (!this.__facet) return;
        this.__facet.refresh([props, this.context]);

        this.cursors = this.__facet.cursors;
        this.facets = this.__facet.facets;

        this.setState(this.__facet.get());
    }

I can send a PR if you like but its only 2 lines of code to add.

**Comment by Yomguithereal** [comment]
Hello @davidtinker. You are right indeed. I forgot this. Would it be possible for you to sketch a PR fixing the issue for mixins and higher-order components etc. also please?

**Comment by Yomguithereal** [comment]
This should be fixed with the latest version of the library. Do you need a retro-compatible fix?
