### ISSUE TITLE
Component `displayName` not found

### ISSUE THREAD

**Issue by LestaD** [Yomguithereal/baobab-react#81]
After i use `branch`.
In react console i see <No display name> component.
How can i fix it?

**Comment by Yomguithereal** [comment]
Hello @LestaD, are you using the v2 or the current released version of `baobab-react`?

**Comment by LestaD** [comment]
Hello @Yomguithereal,  i use `0.1.1`

**Comment by Yomguithereal** [comment]
@LestaD, can you show me some of the incriminated code. I can't find any usage of `displayName` in the `0.1.1` version.
