### ISSUE TITLE
Meaning for action rebinding

### ISSUE THREAD

**Issue by ivan-kleshnin** [Yomguithereal/baobab-react#83]
So we have now two possible keys: `cursors` and `actions`

```js
@branch({
  cursors: {
    colors: ['colors']
  },
  actions: {
    add: actions.addColor
  }
})
```

instead of previous API:

```js
@branch({
  colors: ['colors']
})
```

What's the reason behind this action rebinding? 
`actions.addColor(...)` is shorter than `this.props.actions.addColor(...)` and requires no additional declarations. Do we get something by passing vanilla functions through `props`?

**Comment by Yomguithereal** [comment]
The binding to the tree through context. Basically it does `fn.bind(null, treeFromContext)`. Else you would have to register `contextTypes` and so on to get the tree etc. This ensures your actions don't depend on the tree but are passed the tree and so it can be hot reloadable easily.

**Comment by ivan-kleshnin** [comment]
Got it, thanks.

**Comment by Yomguithereal** [comment]
I would have liked to keep the simple 

```js
@branch({
  colors: ['colors']
})
```

but I guess it's more simple to migrate to v2 without and more easily extendable in the future if needed.
