### ISSUE TITLE
action function returns TypeError

### ISSUE THREAD

**Issue by henriklundgren** [Yomguithereal/baobab-react#85]
`Uncaught TypeError: path.some is not a function`.

**Comment by Yomguithereal** [comment]
Hello @henriklundgren. Could you provide some more context to your issue. I cannot do anything really without more information. Thanks.

**Comment by henriklundgren** [comment]
Sure,
https://gist.github.com/henriklundgren/c152827339684b6c2169

**Comment by demux** [comment]
[line 36](https://gist.github.com/henriklundgren/c152827339684b6c2169#file-index-js-L36)
Each cursor needs to be a list.

**Comment by henriklundgren** [comment]
@demux solved it.

Though, the changes aren't propagating to the view. I would assume it has something about React not knowing the previous state.

**Comment by Yomguithereal** [comment]
Yes, this is strange that this won't be allowed by the library. It would be consistent with the lib's polymorphisms.

**Comment by Yomguithereal** [comment]
Just opened #86 for it.
