### ISSUE TITLE
es7 decorators error

### ISSUE THREAD

**Issue by tonypee** [Yomguithereal/baobab-react#87]
I have installed using npm, and the decorator code throws an error running through babel 5.8: 

Uncaught TypeError: (0 , _baobabReactDecorators2.default) is not a function

The code of the in node_modules is es5, and looks something like: 

function root(tree) {
  return function (Component) {
    return (0, _higherOrderJs.root)(Component, tree);
  };
}

So, the error makes sense. Is it my version of babel - or maybe the code that is output to node_modules?

**Comment by tonypee** [comment]
Looks like the issue is in the browserify compile. It should look like this:

var _higherOrderJs = require('./higher-order.js');

function root(tree) {
  return function (Component) {
    return _higherOrderJs.root(Component, tree);
  };
}

**Comment by Yomguithereal** [comment]
Hello @tonypee. Which `baobab-react` version are you using? I am using the latest one and never had a single issue with it. Is the code you are working on Open Source per chance so I can help you better?

**Comment by tonypee** [comment]
Its baobab-react@1.0.0. I am using webkit for my build. Maybe thats it. Webkit cant build this code:

var test = function() { console.log('test') }
(0, test)()

Are you using browserify?

**Comment by tonypee** [comment]
scratch that - it just needs a semicolon on the 1st line. I can get it to work using:

``` var branch from 'baobab-react/decorators').branch; ```

but when i try the es6 module format:

``` import branch from 'baobab-react/decorators'; ```

it errors:
Uncaught TypeError: (0 , _baobabReactDecorators2.default) is not a function. Ill explore more if this is an issue with babel.

**Comment by psypersky** [comment]
@tonypee  Shouldn't you import with "import {branch} from 'baobab-react/decorators'; ?

**Comment by tonypee** [comment]
yup - sorry, this was back when i was just starting with es ;) my bad
