### ISSUE TITLE
Warning of invalid prop type

### ISSUE THREAD

**Issue by jemos** [Yomguithereal/baobab-react#98]
Hi,

I'm having this warning:
`Warning: Failed Context Types: prop type tree is invalid; it must be a Baobab tree. Check the render method of MyApp.`

But from the log I can see:
```
bundle.js:143 MyApp.render()
2016-02-26 15:08:44.309 bundle.js:144   context.tree = undefined
2016-02-26 15:08:44.310 bundle.js:145   props.tree = [object Baobab]
```

And the way I create the root view is:

```
var renderApp = function() {
	var root = (<MyApp tree={AppState}/>);
	ReactDOM.render(root, document.querySelector('#myapp'));
};
```

Any idea of what could be the issue? It does render all the components OK but it is giving this annoying warning... when rendering the root view as well the child views..

Thanks for your help.

**Comment by Yomguithereal** [comment]
Did you use the `root` mixin or higher order function to provide the tree as context to your React app?

**Comment by jemos** [comment]
Ah yes, in MyApp I've:

```
var MyApp= React.createClass({
	mixins: [mixins.root],
...
```

And in the child components I've for example:

```
module.exports.LibraryManagerSideBar = React.createClass({
	mixins: [mixins.branch],
...
```

I don't think it's a problem of baobab-react module but I thought in asking here because someone else could have the same issue before.

**Comment by Yomguithereal** [comment]
Do you happen to tamper with context or use other library relying on context?

**Comment by jemos** [comment]
Hi,

I'm not using other libraries that rely on context (if I dump the context I see there only .tree).

Later I can try debug it more and see if I find the issue..

Thanks.

**Comment by Yomguithereal** [comment]
If your code is public somewhere I can take a look if you want.

**Comment by jemos** [comment]
It seems to be something related with the require/browserify flow. I noticed that inside the module where I create the Baobab state tree instanceof is true, but after the require() function return it becomes false.

I've synced a simple test case to https://github.com/jemos/baobab-testcase

**Comment by jemos** [comment]
I've found the problem.. I didn't knew browserify/require would look up the directory hierarchy when not found the module locally.. so I had duplicate modules in the bundle. My bad. Thanks anyway!

**Comment by Yomguithereal** [comment]
On a side note, maybe I should stop relying on `instanceof` anyway.
